#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"

struct RobotMap
{
	const static u_int32_t
		FRONT_LEFT_MOTOR_PORT = 5,
		FRONT_RIGHT_MOTOR_PORT = 7,
		REAR_LEFT_MOTOR_PORT = 4,
		REAR_RIGHT_MOTOR_PORT = 6,
		PADDLE_LEFT_MOTOR_PORT = 1,
		PADDLE_RIGHT_MOTOR_PORT = 0,
		PADDLE_ENCODER_CHANNEL_A = 0,
		PADDLE_ENCODER_CHANNEL_B = 1,
		CLAW_LIFTER_PORT = 2,
		CLAW_GRABBER_PORT = 3,
		CLAW_LIMIT_SWITCH_LOWER = 3,
		CLAW_LIMIT_SWITCH_UPPER = 2;
};

#endif
